name: Create Release Candidate

on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: 'Source Branch/Tag/SHA'
        required: true
        default: 'main'

      target_version:
        description: 'Target Version [syntax: v3.2.1]'
        required: true
        default: 'auto'

      previous_version:
        description: 'Previous Version'
        required: true
        default: 'auto'

jobs:
  process-inputs:
    name: Create Release Candidate
    runs-on: ubuntu-20.04

    env:
      DEFAULT_VERSION: v1.0.0
      PROJECT_ROOT_DIR: ../../../
      RELEASE_CONFIG: ../../release.yml

    outputs:
      target_version: ${{ steps.process_versions.outputs.target_version }}
      previous_version: ${{ steps.process_versions.outputs.previous_version }}
      release_notes: ${{ steps.process_release_notes.outputs.release_notes }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: pip3 install -r requirements.txt
        working-directory: .github/workflows/releases

      - name: Process Target and Previous versions
        run: |
          VERSIONS=$(python3 scripts/get_versions.py \
            --config ${{ env.RELEASE_CONFIG }} \
            --target-version ${{ inputs.target_version }} \
            --previous-version ${{ inputs.previous_version }} \
            --default-version ${{ env.DEFAULT_VERSION }} \
            --source-branch ${{ inputs.source_branch }})

          echo ${VERSIONS}

          echo ::set-output name=target_version::$(echo ${VERSIONS} | jq -r '.target_version')
          echo ::set-output name=previous_version::$(echo ${VERSIONS} | jq -r '.previous_version')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: .github/workflows/releases
        id: process_versions

      - name: Generate Release Notes
        run: |
          RELEASE_NOTES=$(python3 scripts/generate_release_notes.py \
            --source-branch ${{ inputs.source_branch }} \
            --root-directory ${{ env.PROJECT_ROOT_DIR }} \
            --target-version ${{ steps.process_versions.outputs.target_version }} \
            --previous-version ${{ steps.process_versions.outputs.previous_version }})

          echo -e "${RELEASE_NOTES}"

          echo ::set-output name=release_notes::${RELEASE_NOTES}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: .github/workflows/releases
        id: process_release_notes

  create-release-candidate:
    needs:
      - process-inputs

    uses: mkochanowski/crucible/.github/workflows/reusable-create-release-candidate.yml@main
    with:
      source_branch: ${{ inputs.source_branch }}
      target_version: ${{ needs.process-inputs.outputs.target_version }}
      release_notes: ${{ needs.process-inputs.outputs.release_notes }}
    secrets: inherit
